import { addDays, dateKey, startOfMonday } from './domain'
import type { CommandData } from './types'

export function createDemoData(now = new Date()): CommandData {
  const monday = startOfMonday(now)
  const today = dateKey(now)
  const logDays = [0, 1, 2, 3, 4, 5, 6]
    .map((offset) => addDays(monday, offset))
    .filter((day) => dateKey(day) <= today)

  const patterns = [
    [30, 90, 30, 60],
    [45, 120, 45, 75],
    [30, 75, 30, 45],
    [60, 135, 30, 60],
    [30, 120, 60, 90],
    [75, 150, 45, 60],
    [30, 90, 30, 60],
  ]

  return {
    logs: logDays.map((day, index) => {
      const [nodeMinutes, dsaMinutes, mathMinutes, jobMinutes] = patterns[index]
      const isToday = dateKey(day) === today
      return {
        day: dateKey(day),
        meditation: !isToday || index % 2 === 0,
        gym: !isToday && index % 3 !== 1,
        diet: isToday ? null : index % 4 === 2 ? 'loose' : 'on_track',
        nodeMinutes: isToday ? 30 : nodeMinutes,
        dsaMinutes: isToday ? 75 : dsaMinutes,
        mathMinutes: isToday ? 15 : mathMinutes,
        jobMinutes: isToday ? 0 : jobMinutes,
        note: '',
      }
    }),
    applications: [
      {
        id: '00000000-0000-4000-8000-000000000101',
        company: 'Atlassian',
        role: 'Graduate Software Engineer',
        lane: 'sde',
        channel: 'india_product',
        status: 'researching',
        windowClosesOn: dateKey(addDays(now, 8)),
        appliedOn: null,
        followUpOn: dateKey(addDays(now, 1)),
        hasReferral: true,
        ctcLpa: null,
        referrerId: '00000000-0000-4000-8000-000000000201',
        jobUrl: '',
        resumeVersion: 'v1',
        resumeDriveUrl: '',
        nextAction: 'Ask for referral, then tailor resume',
        notes: '',
      },
      {
        id: '00000000-0000-4000-8000-000000000102',
        company: 'Razorpay',
        role: 'Software Engineer — Backend',
        lane: 'sde',
        channel: 'gcc',
        status: 'applied',
        windowClosesOn: null,
        appliedOn: dateKey(addDays(now, -4)),
        followUpOn: dateKey(now),
        hasReferral: false,
        ctcLpa: 24,
        referrerId: null,
        jobUrl: '',
        resumeVersion: 'v1',
        resumeDriveUrl: '',
        nextAction: 'Follow up with campus recruiter',
        notes: '',
      },
      {
        id: '00000000-0000-4000-8000-000000000103',
        company: 'Sarvam AI',
        role: 'ML Engineer Intern',
        lane: 'ai_ml',
        channel: 'remote_intl',
        status: 'oa',
        windowClosesOn: null,
        appliedOn: dateKey(addDays(now, -7)),
        followUpOn: dateKey(addDays(now, 3)),
        hasReferral: true,
        ctcLpa: null,
        referrerId: null,
        jobUrl: '',
        resumeVersion: 'v2',
        resumeDriveUrl: '',
        nextAction: 'Complete evaluation by Friday',
        notes: '',
      },
      {
        id: '00000000-0000-4000-8000-000000000104',
        company: 'Example Systems',
        role: 'Associate Software Engineer',
        lane: 'sde',
        channel: 'services',
        status: 'rejected',
        windowClosesOn: null,
        appliedOn: dateKey(addDays(now, -30)),
        followUpOn: null,
        hasReferral: false,
        ctcLpa: null,
        referrerId: null,
        jobUrl: '',
        resumeVersion: 'v1',
        resumeDriveUrl: '',
        nextAction: '',
        notes: 'Closed after screening.',
      },
    ],
    people: [
      {
        id: '00000000-0000-4000-8000-000000000201',
        name: 'Ananya Rao',
        company: 'Atlassian',
        email: '',
        linkedinUrl: '',
        howKnown: 'linkedin',
        status: 'to_reach_out',
        lastContactOn: null,
        nextFollowUpOn: dateKey(now),
        notes: '',
      },
      {
        id: '00000000-0000-4000-8000-000000000202',
        name: 'Kabir Mehta',
        company: 'Razorpay',
        email: '',
        linkedinUrl: '',
        howKnown: 'alumni',
        status: 'talking',
        lastContactOn: dateKey(addDays(now, -5)),
        nextFollowUpOn: dateKey(addDays(now, 2)),
        notes: '',
      },
    ],
    projects: [
      {
        id: '00000000-0000-4000-8000-000000000301',
        name: 'RAG evaluation workbench',
        type: 'portfolio',
        status: 'active',
        client: '',
        paymentStatus: 'na',
        amount: null,
        currency: 'INR',
        isPublic: false,
        deadlineOn: dateKey(addDays(now, 5)),
        repoUrl: '',
        demoUrl: '',
        driveFolderUrl: '',
        nextAction: 'Publish baseline metrics and README',
        content: '',
      },
      {
        id: '00000000-0000-4000-8000-000000000302',
        name: 'Client document classifier',
        type: 'freelance',
        status: 'blocked',
        client: 'Sample client',
        paymentStatus: 'unpaid',
        amount: null,
        currency: 'INR',
        isPublic: false,
        deadlineOn: dateKey(addDays(now, 2)),
        repoUrl: '',
        demoUrl: '',
        driveFolderUrl: '',
        nextAction: 'Get labelled samples from client',
        content: '',
      },
    ],
    ideas: [
      {
        id: '00000000-0000-4000-8000-000000000401',
        idea: 'Placement-prep spaced-repetition shell for Indian colleges',
        problem: 'Students lose useful interview patterns in disconnected notes.',
        targetMarket: 'Indian engineering students',
        monetization: '',
        status: 'captured',
        nextAction: 'Ask three seniors if they would pay',
      },
      {
        id: '00000000-0000-4000-8000-000000000402',
        idea: 'Weekly auto-digest of GCC roles for freshers',
        problem: 'Relevant fresher roles are scattered across company sites.',
        targetMarket: 'Early-career software candidates',
        monetization: '',
        status: 'exploring',
        nextAction: 'Draft the scrape-and-rank pipeline',
      },
    ],
    learning: [
      {
        id: '00000000-0000-4000-8000-000000000501',
        concept: 'Sliding window: variable size',
        stack: 'brain',
        track: 'dsa',
        itemType: 'pattern',
        confidence: 2,
        difficulty: 'medium',
        nextReviewOn: dateKey(now),
        lastReviewedOn: null,
        masteryHits: 0,
        sourceUrl: '',
        content: 'Expand the right edge, then shrink from the left while the constraint is violated. Track the best valid window after restoring the invariant.',
      },
      {
        id: '00000000-0000-4000-8000-000000000502',
        concept: 'Node event-loop phases',
        stack: 'job',
        track: 'node',
        itemType: 'concept',
        confidence: 3,
        difficulty: 'medium',
        nextReviewOn: dateKey(addDays(now, -1)),
        lastReviewedOn: null,
        masteryHits: 0,
        sourceUrl: '',
        content: 'Timers, pending callbacks, idle/prepare, poll, check, then close callbacks. Promise microtasks run between operations; process.nextTick has its own priority queue.',
      },
      {
        id: '00000000-0000-4000-8000-000000000503',
        concept: 'Bayes theorem from conditional probability',
        stack: 'brain',
        track: 'math',
        itemType: 'formula',
        confidence: 4,
        difficulty: 'hard',
        nextReviewOn: dateKey(now),
        lastReviewedOn: null,
        masteryHits: 1,
        sourceUrl: '',
        content: 'P(A|B) = P(B|A)P(A) / P(B). The denominator normalizes the likelihood-weighted prior over all possible causes.',
      },
    ],
  }
}
