import type { EntityFieldDefinition, EntityType } from './types'

const TYPE_IDS = {
  application: '10000000-0000-4000-8000-000000000001',
  person: '10000000-0000-4000-8000-000000000002',
  project: '10000000-0000-4000-8000-000000000003',
  learning: '10000000-0000-4000-8000-000000000004',
  note: '10000000-0000-4000-8000-000000000005',
} as const

type FieldOptions = Partial<Pick<EntityFieldDefinition, 'required' | 'listVisible' | 'filterable' | 'options'>>

function field(
  key: string,
  label: string,
  kind: EntityFieldDefinition['kind'],
  options: FieldOptions = {},
): EntityFieldDefinition {
  return {
    key,
    label,
    kind,
    required: options.required ?? false,
    listVisible: options.listVisible ?? false,
    filterable: options.filterable ?? false,
    deprecated: false,
    options: options.options ?? [],
  }
}

export function createBuiltInEntityTypes(): EntityType[] {
  return [
    {
      id: TYPE_IDS.application,
      typeKey: 'application',
      singularName: 'Application',
      pluralName: 'Applications',
      iconKey: 'application',
      schemaVersion: 2,
      fields: [
        field('company', 'Company', 'text', { required: true, listVisible: true, filterable: true }),
        field('role', 'Role', 'text', { required: true, listVisible: true, filterable: true }),
        field('lane', 'Lane', 'single_select', { required: true, filterable: true, options: ['sde', 'ai_ml'] }),
        field('channel', 'Channel', 'single_select', { required: true, filterable: true, options: ['india_product', 'gcc', 'remote_intl', 'services'] }),
        field('status', 'Status', 'single_select', { required: true, listVisible: true, filterable: true, options: ['researching', 'applied', 'oa', 'phone', 'onsite', 'offer', 'rejected'] }),
        field('applied_on', 'Applied on', 'date', { filterable: true }),
        field('has_referral', 'Has referral', 'boolean', { required: true, filterable: true }),
        field('ctc_lpa', 'CTC (LPA)', 'number'),
        field('referrer_id', 'Referrer id', 'text'),
        field('job_url', 'Job URL', 'url'),
        field('resume_version', 'Resume version', 'text'),
        field('resume_drive_url', 'Resume Drive URL', 'url'),
        field('next_action', 'Next action', 'textarea', { listVisible: true }),
        field('notes', 'Notes', 'textarea'),
      ],
      defaultSortField: 'updated_at',
      defaultSortDirection: 'desc',
      groupByField: 'status',
      allowedCommitmentKinds: ['follow-up', 'deadline', 'milestone'],
      pluginKey: null,
      isActive: true,
    },
    {
      id: TYPE_IDS.person,
      typeKey: 'person',
      singularName: 'Person',
      pluralName: 'People',
      iconKey: 'person',
      schemaVersion: 2,
      fields: [
        field('company', 'Company', 'text', { listVisible: true, filterable: true }),
        field('email', 'Email', 'text'),
        field('linkedin_url', 'LinkedIn URL', 'url'),
        field('how_known', 'How known', 'single_select', { filterable: true, options: ['cold', 'alumni', 'linkedin', 'ex_colleague', 'referred_by'] }),
        field('status', 'Status', 'single_select', { required: true, listVisible: true, filterable: true, options: ['to_reach_out', 'talking', 'referred', 'cold'] }),
        field('last_contacted_on', 'Last contacted on', 'date', { filterable: true }),
        field('notes', 'Notes', 'textarea'),
      ],
      defaultSortField: 'title',
      defaultSortDirection: 'asc',
      groupByField: 'status',
      allowedCommitmentKinds: ['contact', 'follow-up'],
      pluginKey: null,
      isActive: true,
    },
    {
      id: TYPE_IDS.project,
      typeKey: 'project',
      singularName: 'Project',
      pluralName: 'Projects',
      iconKey: 'project',
      schemaVersion: 2,
      fields: [
        field('project_type', 'Type', 'single_select', { required: true, listVisible: true, filterable: true, options: ['internship', 'freelance', 'portfolio'] }),
        field('status', 'Status', 'single_select', { required: true, listVisible: true, filterable: true, options: ['active', 'blocked', 'review', 'done'] }),
        field('client', 'Client', 'text', { listVisible: true, filterable: true }),
        field('payment_status', 'Payment status', 'single_select', { required: true, filterable: true, options: ['na', 'unpaid', 'invoiced', 'paid'] }),
        field('amount', 'Amount', 'number'),
        field('currency', 'Currency', 'text', { required: true }),
        field('is_public', 'Public', 'boolean', { required: true, listVisible: true, filterable: true }),
        field('repo_url', 'Repository URL', 'url'),
        field('demo_url', 'Demo URL', 'url'),
        field('drive_folder_url', 'Drive folder URL', 'url'),
        field('next_action', 'Next action', 'textarea', { listVisible: true }),
        field('content_markdown', 'Content', 'textarea'),
      ],
      defaultSortField: 'updated_at',
      defaultSortDirection: 'desc',
      groupByField: 'status',
      allowedCommitmentKinds: ['deadline', 'review', 'milestone'],
      pluginKey: null,
      isActive: true,
    },
    {
      id: TYPE_IDS.learning,
      typeKey: 'learning',
      singularName: 'Learning item',
      pluralName: 'Learning',
      iconKey: 'learning',
      schemaVersion: 2,
      fields: [
        field('stack', 'Stack', 'single_select', { required: true, filterable: true, options: ['job', 'brain'] }),
        field('track', 'Track', 'single_select', { required: true, listVisible: true, filterable: true, options: ['node', 'dsa', 'math'] }),
        field('item_type', 'Item type', 'single_select', { required: true, filterable: true, options: ['concept', 'pattern', 'snippet', 'formula'] }),
        field('confidence', 'Confidence', 'number', { required: true, listVisible: true, filterable: true }),
        field('difficulty', 'Difficulty', 'single_select', { filterable: true, options: ['easy', 'medium', 'hard'] }),
        field('last_reviewed_on', 'Last reviewed on', 'date', { filterable: true }),
        field('mastery_hits', 'Mastery hits', 'number', { required: true }),
        field('source_url', 'Source URL', 'url'),
        field('content_markdown', 'Content', 'textarea'),
      ],
      defaultSortField: 'updated_at',
      defaultSortDirection: 'desc',
      groupByField: 'track',
      allowedCommitmentKinds: ['review', 'drill'],
      pluginKey: 'spaced_repetition',
      isActive: true,
    },
    {
      id: TYPE_IDS.note,
      typeKey: 'note',
      singularName: 'Note',
      pluralName: 'Notes',
      iconKey: 'note',
      schemaVersion: 2,
      fields: [
        field('tag', 'Tag', 'single_select', { required: true, listVisible: true, filterable: true, options: ['idea'] }),
        field('problem', 'Problem', 'textarea'),
        field('target_market', 'Target market', 'textarea'),
        field('monetization', 'Monetization', 'textarea'),
        field('status', 'Status', 'single_select', { required: true, listVisible: true, filterable: true, options: ['captured', 'exploring', 'validating', 'dropped'] }),
        field('next_action', 'Next action', 'textarea', { listVisible: true }),
      ],
      defaultSortField: 'updated_at',
      defaultSortDirection: 'desc',
      groupByField: 'status',
      allowedCommitmentKinds: [],
      pluginKey: null,
      isActive: true,
    },
  ]
}
